-- Migration 014 down: Revert RLS hardening.

-- 3. Restore DEFAULT PRIVILEGES
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO heritage_app;

-- 2. Remove RLS from audit_log
DROP POLICY IF EXISTS audit_log_tenant_read ON audit_log;
ALTER TABLE audit_log DISABLE ROW LEVEL SECURITY;

-- 1. Remove FORCE from business tables
ALTER TABLE users NO FORCE ROW LEVEL SECURITY;
ALTER TABLE vehicles NO FORCE ROW LEVEL SECURITY;
ALTER TABLE bays NO FORCE ROW LEVEL SECURITY;
ALTER TABLE events NO FORCE ROW LEVEL SECURITY;
ALTER TABLE tasks NO FORCE ROW LEVEL SECURITY;
ALTER TABLE documents NO FORCE ROW LEVEL SECURITY;
ALTER TABLE refresh_tokens NO FORCE ROW LEVEL SECURITY;
